name: Deploy

on:
    push:
        branches:
            - master

# jobs:
#     deploy_lambda:
#         runs-on: ubuntu-latest
#         steps:
#             - uses: actions/checkout@v2
#             - uses: actions/setup-node@v2
#               with:
#                 node-version: '12'
#             - name: npm install
#               env:
#                 CI: true
#               run: |
#                 npm ci

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '22'
      - name: Clear npm cache
        run: npm cache clean --force
      - name: npm install
        env:
          CI: true
        run: |
          npm ci